server:
  server_name: site1.com
  ip: 0.0.0.0
  port: 5000
  root: ./www/site1
  body_size: 500
  default_errors:
    error 404: ./public/html/404.html
    error 405: ./public/html/405.html
    error 406: ./public/html/foca.html
  location: /
    file: index.html
    methods:
      GET: on
      POST: on
      DELETE: on
  location: /goto42
    file: potxolo.html
    redirect: www.42urduliz.com
  location: /ai
    autoindex: on
    upload_folder: /upload
  location: /favicon.ico
    file: icon1.png
  location: /images/sample
    file: images/sample_image1.jpg

server:
  server_name: site2.com
  ip: 127.0.0.1
  port: 5001
  root: ./www/site2
  location: /
    file: index.html
  location: /favicon.ico
    file: icon2.png
  location: /images/sample
    file: images/sample_image2.png

server:
  server_name: susmuelas.com
  ip: 127.8.8.1
  port: 5002
  port: 6001
  root: ./www/susmuelas
  location: /
    file: index.html
  location: /favicon.ico
    file: iconSM.png
  location: /cgi-bin/
  location: /images/sample
    methods:
      GET: on
      POST: metodo_chungas
      DELETE: on
      file: images/muelaimg.png