server:
  server_name: site2.com
  ip: 127.0.0.1
  port: 61002
  root: ./www/site2
  location: /
    file: index.html
  location: /favicon.ico
    file: icon2.png
  location: /images/sample
    file: images/sample_image2.png